# Generated by Django 4.1 on 2022-09-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_days', models.CharField(max_length=25)),
                ('leave_reason', models.CharField(max_length=300)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp1.employee')),
            ],
        ),
    ]
